@startuml

title JT1078组件交互示意图

actor [用户1]
actor [用户2]
component [车载终端]
component [Web服务器]
component [JT1078信令服务器]
component [JT1078流媒体服务器]
component [HLS服务器]
component [RTMP服务器]

[用户1] -[#007ED6]> [Web服务器]: 点击UI实时直播按钮
[用户2] -[#007ED6]> [Web服务器]: 点击UI实时直播按钮

[Web服务器] -[#007ED6]> [JT1078信令服务器]: 请求实时直播视频
[JT1078信令服务器] <-[#007ED6]> [JT1078流媒体服务器]: 请求流媒体接收地址
[JT1078信令服务器] -[#007ED6]> [车载终端]: 下发0x0901指令
[车载终端] ..[#FF0000]> [JT1078流媒体服务器]: 发送RTP媒体流

[JT1078流媒体服务器] ..[#FF0000]> [HLS服务器]: 打包HLS切片
[用户1] <..[#FF0000]> [HLS服务器]: 拉取HLS切片

[JT1078流媒体服务器] ..[#FF0000]> [RTMP服务器]: 封装音视频流
[RTMP服务器] ..[#FF0000]> [用户2]: 发送RTMP音视频流

@enduml
